baseURL: "https://mundeweddings.netlify.app/"
title: M&E Wedding 06 Aug 2022
theme: airspace-hugo
timeZone: UTC
paginate: '4'
summaryLength: '30'
disableLanguages: []
disqusShortname: ''
googleAnalytics: ''
module:
  hugoVersion:
    extended: yes
    min: 0.87.0
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    endLevel: 6
    ordered: no
    startLevel: 2
params:
  author: Themefisher
  contact:
    address_descriptors: no
    email: demo@email.com
    form:
      action: '#'
      enable: yes
      success_image: images/paper-plane.svg
      use_netlify: yes
    location: "\r\n**Themefisher**  \r\nNorth Main Street  \r\nBrooklyn, New South
      Wales  \r\nAustralia\r\n"
    phone: 0124857985320
  cookies:
    enable: yes
    expire_days: 2
  counter:
    enable: yes
    username: ''
  description: This is meta description
  gmap:
    enable: yes
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  image: images/logom_e6.png
  logo: images/logom_e6.png
  logo_width: 151px
  plugins:
    css:
      - attributes: media='screen'
        link: plugins/bootstrap/css/bootstrap.min.css
      - attributes: ''
        link: plugins/ionicons/css/ionicons.min.css
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.css
      - attributes: ''
        link: plugins/slick/slick.css
    js:
      - attributes: ''
        link: plugins/jquery/jquery.min.js
      - attributes: ''
        link: plugins/bootstrap/js/bootstrap.min.js
      - attributes: ''
        link: plugins/slick/slick.min.js
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.js
      - attributes: ''
        link: plugins/shuffle/shuffle.min.js
      - attributes: defer
        link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  social:
    - icon: ion-social-googleplus-outline
      link: '#'
    - icon: ion-social-linkedin-outline
      link: '#'
    - icon: ion-social-pinterest-outline
      link: '#'
    - icon: ion-social-dribbble-outline
      link: '#'
    - icon: ion-social-twitter-outline
      link: '#'
    - icon: ion-social-facebook-outline
      link: '#'
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
languages:
  de:
    contentDir: content/german
    copyright: Copyright &copy; 2021 [Themefisher](https://themefisher.com). Alle
      Rechte vorbehalten.
    languageCode: de-DE
    languageName: Deutsch
    menu:
      main:
        - hasChildren: yes
          name: Mehr
          weight: 5
    weight: 3
  en:
    contentDir: content/english
    copyright: 
    languageCode: en-US
    languageName: English
    menu:
      main:
        - hasChildren: yes
          name: More
          weight: 5
    weight: 1
  fr:
    contentDir: content/french
    copyright: Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tous
      droits réservés.
    languageCode: fr-FR
    languageName: Français
    menu:
      main:
        - hasChildren: yes
          name: Plus
          weight: 5
    weight: 2
  it:
    contentDir: content/italian
    copyright: Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti
      i diritti riservati.
    languageCode: it-IT
    languageName: Italiano
    menu:
      main:
        - hasChildren: yes
          name: Più
          weight: 5
    weight: 2
